name: Generate Cred Instance
on:
  # Trigger on merging to master.
  push:
    branches:
      - main
  # As well as every 24 hours (at 0:00 UTC).
  schedule:
    - cron: 0 17 * * *
  workflow_dispatch:

jobs:
  GenerateCredInstance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'gh-pages'

      - name: Remove old cache from gh-pages branch
        run: |
          rm -r -f cache ||:
          git config user.name 'credbot'
          git config user.email 'credbot@users.noreply.github.com'
          git add .
          git commit --amend --no-edit
          git push --force-with-lease
          
      - uses: actions/checkout@v2
        with:
          ref: 'main'
          persist-credentials: false # Required to make github pages deployment work correctly

      - name: Cache Data # Cache SourceCred Data, invalidating if any of the config changes or the SC version is updated
        uses: actions/cache@v3.2.5
        with:
          path: '**/cache'
          key: SC-${{ runner.os }}-${{ hashFiles('**/config.json', '**/sourcecred.json', '**/yarn.lock') }}

      - name: Install Packages 🔧
        run: yarn --frozen-lockfile

      - name: Load Data and Compute Cred 🧮
        run: |
          yarn load
          yarn sourcecred contributions
          yarn sourcecred credequate
        env:
          SOURCECRED_GITHUB_TOKEN: ${{ secrets.SOURCECRED_GITHUB_TOKEN }}
          SOURCECRED_DISCORD_TOKEN: ${{ secrets.SOURCECRED_DISCORD_TOKEN }}

      - name: Generate Frontend 🏗
        run: |
          yarn sourcecred site
          rm -rf ./site/{output,data,config,sourcecred.json,package.json,yarn.lock,cache}
          cp -r ./{output,data,config,sourcecred.json,package.json,yarn.lock,cache} ./site/

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          token: ${{ secrets.SOURCECRED_GITHUB_TOKEN }}
          branch: gh-pages
          folder: site
